### ISSUE TITLE
try 3-way comparison

### ISSUE THREAD

**Issue by abremges** [philippmuench/Donut#13]
it should be possible to visualize 3-way comparisons.
not sure how messy it gets, but worth a try – IMHO.
that's what Johannes or Susi wished for back then.

**Comment by philippmuench** [comment]
what do you mean, three genomes? The currenct implementation is not limited to some number of genomes you just can put any number of fasta files in the `genomes` folder and it should work.

Maybe this gets tricky when drawing the lines of the pairwise ORF comparisons, because I have to made pairwise alignments * number of genomes...

**Comment by philippmuench** [comment]
see example at 78e6a03

**Comment by abremges** [comment]
My bad, I assumed that only 2-way was implemented by now (because the former example showed only 2 genomes). Might get tricky, as you noted, when you draw the lines eventually. There is some way to optimize the ordering of contigs to minimize crossovers between lines and ribbons – at least in the original Circos implementation, as a helper script (if I remember correctly). But we can worry about that once we see first results. Thanks!

**Comment by philippmuench** [comment]
good to know, thanks, I will try this.
